image: node:16

pipelines:
  default:
  - step:
      name: Build development
      caches:
        - node
      script:
        - yarn
        - yarn dev

  - step:
      name: Test
      caches:
        - node
      script:
        - yarn test

  - step:
      name: Build production
      caches:
        - node
      script:
        - yarn build